name: Deploy package to PyPI

on:
  release:
    types: [published]

jobs:
  build-source-package-and-wheels:
    uses: ./.github/workflows/build-source-package-and-wheels.yml
    with:
      github-ref-name: ${{ github.ref_name }}

  deploy:
    needs:
      - build-source-package-and-wheels
    environment:
      name: pypi
      url: https://pypi.org/project/stream-unzip/

    name: upload release to PyPI
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./dist

      # The "merge-multiple" option of download-artifact seems to cause corruption when there are
      # multiple files of the same name, which happens because in some different macOS versions
      # make the exact same Python package. So we avoid that and do a manual move of packages
      # to the top level for upload
      - name: Move packages to top level
        run: |
          find ./dist -mindepth 2 -type f -exec mv -f -t ./dist '{}' ';'
          rm -R -- ./dist/*/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: ./dist/
